apiVersion: v1
kind: Service
metadata:
  name: {{ include "wedding.fullname" . }}-service
spec:
  selector:
    app: wedding
  ports:
  - name: wedding
    protocol: TCP
    port: 3000
    targetPort: 80
